services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pmt_db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3308:3306" 
    networks:
      - pmt-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: ./Backend_PMT
    container_name: backend
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - pmt-network

  frontend:
    build: ./Frontend_PMT
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8080/api
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - pmt-network
    volumes:
      - ./Frontend_PMT:/app
      - /app/node_modules

volumes:
  mysql-data:

networks:
  pmt-network:
    driver: bridge